# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-11 19:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_id', models.IntegerField()),
                ('study_id', models.IntegerField()),
                ('form_name', models.CharField(max_length=500)),
                ('form_description', models.TextField()),
                ('log_form', models.CharField(max_length=500)),
                ('globl_library', models.CharField(max_length=10)),
                ('globl_name', models.CharField(max_length=500)),
                ('sdv', models.CharField(max_length=50)),
            ],
        ),
    ]
